config/routes.rb
Rails.application.routes.draw do
  resources :scaffoldtests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/scaffoldtest.rb
class Scaffoldtest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/scaffoldtests_controller.rb
class ScaffoldtestsController < ApplicationController
  before_action :set_scaffoldtest, only: [:show, :edit, :update, :destroy]

  # GET /scaffoldtests
  # GET /scaffoldtests.json
  def index
    @scaffoldtests = Scaffoldtest.all
  end

  # GET /scaffoldtests/1
  # GET /scaffoldtests/1.json
  def show
  end

  # GET /scaffoldtests/new
  def new
    @scaffoldtest = Scaffoldtest.new
  end

  # GET /scaffoldtests/1/edit
  def edit
  end

  # POST /scaffoldtests
  # POST /scaffoldtests.json
  def create
    @scaffoldtest = Scaffoldtest.new(scaffoldtest_params)

    respond_to do |format|
      if @scaffoldtest.save
        format.html { redirect_to @scaffoldtest, notice: 'Scaffoldtest was successfully created.' }
        format.json { render :show, status: :created, location: @scaffoldtest }
      else
        format.html { render :new }
        format.json { render json: @scaffoldtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scaffoldtests/1
  # PATCH/PUT /scaffoldtests/1.json
  def update
    respond_to do |format|
      if @scaffoldtest.update(scaffoldtest_params)
        format.html { redirect_to @scaffoldtest, notice: 'Scaffoldtest was successfully updated.' }
        format.json { render :show, status: :ok, location: @scaffoldtest }
      else
        format.html { render :edit }
        format.json { render json: @scaffoldtest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scaffoldtests/1
  # DELETE /scaffoldtests/1.json
  def destroy
    @scaffoldtest.destroy
    respond_to do |format|
      format.html { redirect_to scaffoldtests_url, notice: 'Scaffoldtest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scaffoldtest
      @scaffoldtest = Scaffoldtest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scaffoldtest_params
      params.require(:scaffoldtest).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scaffoldtests_helper.rb
module ScaffoldtestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstraptest</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><a href="#">Bootstrapテキストページ</a></li>
        <li><a href="#">トップページ</a></li>
      </ul>
    </header>

  <%= yield %>

    <footer>
      <p>運営会社DIVE INTO CODE株式会社</p>
      <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
    </footer>

  </body>
</html>

app/views/scaffoldtests/_form.html.erb
<%= form_with(model: scaffoldtest, local: true) do |form| %>
  <% if scaffoldtest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scaffoldtest.errors.count, "error") %> prohibited this scaffoldtest from being saved:</h2>

      <ul>
      <% scaffoldtest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :scaffoldtest_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scaffoldtests/edit.html.erb
<h1>Editing Scaffoldtest</h1>

<%= render 'form', scaffoldtest: @scaffoldtest %>

<%= link_to 'Show', @scaffoldtest %> |
<%= link_to 'Back', scaffoldtests_path %>

app/views/scaffoldtests/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Scaffoldtests</h1>

<table>
  <div class="theme">
    <thead>
      <tr>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </div>
  <div class="contents">

    <div class="blog-panel">
    <tbody>
      <% @scaffoldtests.each do |scaffoldtest| %>
          <tr>
            <td><%= scaffoldtest.content %></td>
            <td><%= link_to 'Show', scaffoldtest, class:'btn btn-default' %></td>
            <td><%= link_to 'Edit', edit_scaffoldtest_path(scaffoldtest), class:"btn btn-info"%></td>
            <td><%= link_to 'Destroy', scaffoldtest, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
          </tr>
      <% end %>
    </tbody>
  </div>
</table>
</div>

<br>

<%= link_to 'New Scaffoldtest', new_scaffoldtest_path %>
</div>

app/views/scaffoldtests/new.html.erb
<h1>New Scaffoldtest</h1>

<%= render 'form', scaffoldtest: @scaffoldtest %>

<%= link_to 'Back', scaffoldtests_path %>

app/views/scaffoldtests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @scaffoldtest.content %>
</p>

<%= link_to 'Edit', edit_scaffoldtest_path(@scaffoldtest) %> |
<%= link_to 'Back', scaffoldtests_path %>